#### Predicting claim frequencies (expected claim count per unit of exposure) expressed as rate. Is the base for key calculations: pricing, resrving, ruin probabilities and reinsurance.

In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing

In [51]:
claimsdf = pd.read_csv('/home/julian/Cursos/Ironhack/Proyectos/ProyectoFinal/freMTPL2freq.csv')

In [52]:
claimsdf.head(3)

IDpol  ClaimNb  Exposure Area  VehPower  VehAge  DrivAge  BonusMalus  \
0    1.0        1      0.10    D         5       0       55          50   
1    3.0        1      0.77    D         5       0       55          50   
2    5.0        1      0.75    B         6       2       52          50   

  VehBrand   VehGas  Density Region  
0      B12  Regular     1217    R82  
1      B12  Regular     1217    R82  
2      B12   Diesel       54    R22

In [4]:
claimsdf.shape

(678013, 12)

In [14]:
claimsdf.dtypes

IDpol         float64
ClaimNb         int64
Exposure      float64
Area           object
VehPower        int64
VehAge          int64
DrivAge         int64
BonusMalus      int64
VehBrand       object
VehGas         object
Density         int64
Region         object
dtype: object

### CATHEGORICAL VARIABLES ENCODING

#### We have 4 cathegorical variables, and 2 cathegorizable ones, namely Vehicle Age and Driver Age

##### VEHICLE BRAND: Non ordinal , 11 CLASES

In [53]:
claimsdf.VehBrand.unique()

array(['B12', 'B6', 'B3', 'B2', 'B5', 'B10', 'B14', 'B13', 'B4', 'B1',
       'B11'], dtype=object)

In [54]:
claimsdf.VehBrand.value_counts()

B12    166024
B1     162736
B2     159861
B3      53395
B5      34753
B6      28548
B4      25179
B10     17707
B11     13585
B13     12178
B14      4047
Name: VehBrand, dtype: int64

In [58]:
dic_brands = {'B1': 1, 'B2': 2, 'B3': 3, 'B4': 4, 'B5': 5, 'B6': 6, 'B10': 7, 'B11': 8, 'B12': 9, 'B13': 10, 'B14': 11}

In [59]:
claimsdf.VehBrand = claimsdf.VehBrand.map(dic_brands)

##### VEHICLE GAS: Non ordinal, 2 CLASES

In [8]:
claimsdf.VehGas.unique()

array(['Regular', 'Diesel'], dtype=object)

In [17]:
claimsdf.VehGas.value_counts()

Regular    345877
Diesel     332136
Name: VehGas, dtype: int64

In [34]:
claimsdf = pd.get_dummies(claimsdf, columns=['VehGas'], drop_first=True)

##### AREA Code: NO ORDINAL ? 6 CLASES

In [9]:
claimsdf.Area.unique()

array(['D', 'B', 'E', 'C', 'F', 'A'], dtype=object)

In [18]:
claimsdf.Area.value_counts()

C    191880
D    151596
E    137167
A    103957
B     75459
F     17954
Name: Area, dtype: int64

##### REGION: Non ordinal,  22 CLASES, Que regiones?

In [10]:
claimsdf.Region.unique()

array(['R82', 'R22', 'R72', 'R31', 'R91', 'R52', 'R93', 'R11', 'R24',
       'R94', 'R83', 'R54', 'R26', 'R53', 'R73', 'R42', 'R25', 'R21',
       'R41', 'R43', 'R74', 'R23'], dtype=object)

In [19]:
claimsdf.Region.value_counts()

R24    160601
R82     84752
R93     79315
R11     69791
R53     42122
R52     38751
R91     35805
R72     31329
R31     27285
R54     19046
R73     17141
R41     12990
R25     10893
R26     10492
R23      8784
R22      7994
R83      5287
R74      4567
R94      4516
R21      3026
R42      2200
R43      1326
Name: Region, dtype: int64

In [63]:
dic_region = {'R11': 1, 'R21': 2, 'R22': 3, 'R23': 4, 'R24': 5, 'R25': 6, 'R26': 7, 
              'R31': 8, 'R41': 9, 'R42': 10, 'R43': 11, 'R52': 12, 'R53': 13, 'R54': 14,
              'R72': 15, 'R73': 16, 'R74': 17, 'R82': 18, 'R83': 19, 'R91': 20, 'R93': 21, 
              'R94': 22}

In [64]:
claimsdf.Region = claimsdf.Region.map(dic_region)

### CATHEGORIZABLES VARIABLES ?

#### VEHICLE POWER (Ordered cathegorical according to the data source)

In [72]:
claimsdf.VehPower.unique()

array([ 5,  6,  7,  4,  9, 15,  8, 10, 12, 11, 14, 13])

In [68]:
claimsdf.VehPower.value_counts()

6     148976
7     145401
5     124821
4     115349
8      46956
10     31354
9      30085
11     18352
12      8214
13      3229
15      2926
14      2350
Name: VehPower, dtype: int64

In [76]:
dic_power = {'4': 1, '5': 2, '6': 3, '7': 4, '8': 5, '9': 6, '10': 7, '11': 8, '12': 9,
             '13': 9, '14': 9, '15': 9}

In [77]:
claimsdf.VehPower = claimsdf.VehPower.map(dic_power)

In [80]:
claimsdf.VehPower

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
678008   NaN
678009   NaN
678010   NaN
678011   NaN
678012   NaN
Name: VehPower, Length: 678013, dtype: float64

#### VEHICLE AGE

In [7]:
claimsdf.VehAge.unique()

array([  0,   2,   1,   9,   8,   4,  10,   5,   3,   6,   7,  15,  25,
        29,  13,  14,  11,  12,  19,  18,  17,  16,  23,  26,  21,  20,
        37,  22,  28,  27,  24,  30,  33,  42,  31,  32,  34,  59,  38,
        39,  46,  35, 100,  43,  44,  36,  40,  78,  99,  48,  41,  47,
        45,  79,  49,  68,  80,  50,  83,  54,  64,  52,  69,  76,  81,
        51,  84,  55,  65,  53,  70,  62,  82,  85,  66,  60,  63,  71])

In [10]:
claimsdf.VehAge.value_counts()

1     71284
2     59124
0     57739
3     50261
4     43492
      ...  
85        1
78        1
60        1
63        1
71        1
Name: VehAge, Length: 78, dtype: int64

#### DRIVER AGE

In [9]:
claimsdf.DrivAge.unique()

array([ 55,  52,  46,  38,  33,  41,  56,  27,  23,  44,  32,  73,  59,
        54,  69,  60,  43,  50,  30,  45,  40,  37,  28,  67,  62,  61,
        42,  51,  53,  31,  65,  47,  75,  39,  22,  24,  48,  26,  49,
        35,  29,  58,  74,  36,  76,  70,  34,  66,  63,  71,  57,  72,
        25,  68,  64,  79,  78,  77,  20,  18,  21,  80,  19,  87,  81,
        95,  86,  84,  88,  83,  90,  93,  82,  85,  91,  89,  99,  94,
        92,  96,  97,  98, 100])

In [11]:
claimsdf.DrivAge.value_counts()

36     17530
38     17346
39     17320
37     17295
52     17195
       ...  
95        24
96        15
97        10
98         5
100        3
Name: DrivAge, Length: 83, dtype: int64

### VARIABLES CONTINUAS log transform??

#### DENSITY

In [23]:
claimsdf.Density.value_counts()

27000    10515
3317      9891
1313      7157
9307      5986
3744      5540
         ...  
1036         2
1013         2
1126         2
869          1
1651         1
Name: Density, Length: 1607, dtype: int64

#### BONUSMALUS, expresado en que unidades?

In [25]:
claimsdf.BonusMalus.unique()

array([ 50,  68,  90, 100,  76,  56,  71,  52,  85,  51,  54,  80,  66,
        72,  55,  53,  60,  95,  64,  57,  58,  91,  62,  97,  74,  61,
        63, 105, 106,  88,  67,  86,  75,  59,  77, 118,  73, 125,  70,
       120,  69,  78,  82, 112,  65,  81, 115,  93,  83,  84,  92, 101,
       109, 110,  79, 102, 140, 147, 156, 108,  96, 107, 132, 148,  87,
       116, 114, 177, 139, 119, 165, 103, 122, 128, 133, 196, 228,  89,
       113,  99, 126, 173, 175, 111, 195, 149, 117, 138, 104, 163, 187,
       158, 230, 185, 198, 151,  94, 208, 176, 136,  98, 135, 142, 162,
       144, 121, 141, 183, 166, 130, 123, 174, 218, 124, 190])

In [24]:
claimsdf.BonusMalus.value_counts()

50     384156
100     19530
68      18791
72      18580
76      18226
        ...  
135         1
136         1
230         1
208         1
151         1
Name: BonusMalus, Length: 115, dtype: int64

### VARIABLE TRANSFORMATIONS

In [26]:
claimsdf['empirical_freq'] = (claimsdf.ClaimNb / claimsdf.Exposure)